// Domain constants shared across services and surfaced to the frontend.
// These are CANONICAL — they mirror BUSINESS_LOGIC_CONTRACT.md exactly.

const ROLES = { ADMIN: 'ADMIN', INSPECTOR: 'INSPECTOR', USER: 'USER' };

const EXTINGUISHER_TYPES = ['WATER', 'CO2', 'FOAM', 'DRY_CHEMICAL'];
const EXTINGUISHER_SIZES = ['1.5_LB', '5_LB', '9_LB', '12_LB'];

// Stored lifecycle statuses (contract §2). EXPIRED is also derived as an overlay.
const EXTINGUISHER_STATUS = {
  AVAILABLE: 'AVAILABLE',
  ASSIGNED: 'ASSIGNED',
  ACTIVE: 'ACTIVE',
  INSPECTION_DUE: 'INSPECTION_DUE',
  UNDER_INSPECTION: 'UNDER_INSPECTION',
  NEEDS_MAINTENANCE: 'NEEDS_MAINTENANCE',
  EXPIRED: 'EXPIRED',
  REPLACEMENT_REQUIRED: 'REPLACEMENT_REQUIRED',
  ARCHIVED: 'ARCHIVED',
};

// Requests (contract §3).
const REQUEST_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  INFO_REQUESTED: 'INFO_REQUESTED',
};
const REQUEST_DECISIONS = ['APPROVE', 'REJECT', 'REQUEST_MORE_INFO'];

// Inspections (contract §4).
const INSPECTION_STATUS = {
  REQUESTED: 'REQUESTED',
  SCHEDULED: 'SCHEDULED',
  UNDER_INSPECTION: 'UNDER_INSPECTION',
  COMPLETED: 'COMPLETED',
  COMPLETED_WITH_ISSUES: 'COMPLETED_WITH_ISSUES',
  CANCELLED: 'CANCELLED',
};
const INSPECTION_RESULT = {
  PASSED: 'PASSED',
  FAILED: 'FAILED',
  NEEDS_MAINTENANCE: 'NEEDS_MAINTENANCE',
  EXPIRED: 'EXPIRED',
  PENDING: 'PENDING',
};

// Maintenance (contract §5).
const MAINTENANCE_STATUS = {
  ACTIVE: 'ACTIVE',
  REPLACEMENT_REQUIRED: 'REPLACEMENT_REQUIRED',
};

// Notifications (contract §6).
const NOTIFICATION_TYPES = [
  'EXT_ASSIGNED', 'REQUEST_SUBMITTED', 'REQUEST_REVIEWED', 'INSPECTION_REQUESTED',
  'INSPECTION_SCHEDULED', 'INSPECTOR_ASSIGNED', 'INSPECTION_DUE', 'INSPECTION_OVERDUE',
  'EXT_EXPIRING', 'EXT_EXPIRED', 'MAINTENANCE_REQUIRED', 'MAINTENANCE_COMPLETED',
];

// Audit (contract §7).
const AUDIT_ACTIONS = {
  ROLE_CHANGED: 'ROLE_CHANGED',
  USER_STATUS_CHANGED: 'USER_STATUS_CHANGED',
  USER_DELETED: 'USER_DELETED',
  USER_CREATED: 'USER_CREATED',
  EXT_ASSIGNED: 'EXT_ASSIGNED',
  EXT_INSTALLED: 'EXT_INSTALLED',
  EXT_ARCHIVED: 'EXT_ARCHIVED',
  REQUEST_REVIEWED: 'REQUEST_REVIEWED',
  INSPECTION_ASSIGNED: 'INSPECTION_ASSIGNED',
  INSPECTION_PERFORMED: 'INSPECTION_PERFORMED',
  MAINTENANCE_LOGGED: 'MAINTENANCE_LOGGED',
};

// Business rule knobs (standards: keep configurable).
const INSPECTION_INTERVAL_MONTHS = 12;
const INSTALL_WINDOW_DAYS = 7;
const EXPIRY_WARNING_DAYS = [30, 60, 90];

module.exports = {
  ROLES,
  EXTINGUISHER_TYPES,
  EXTINGUISHER_SIZES,
  EXTINGUISHER_STATUS,
  REQUEST_STATUS,
  REQUEST_DECISIONS,
  INSPECTION_RESULT,
  INSPECTION_STATUS,
  MAINTENANCE_STATUS,
  NOTIFICATION_TYPES,
  AUDIT_ACTIONS,
  INSPECTION_INTERVAL_MONTHS,
  INSTALL_WINDOW_DAYS,
  EXPIRY_WARNING_DAYS,
};
